# Site title and subtitle. This is used in _includes/header.html
title: 'Travelguide-Docs'
subtitle: '项目相关文档'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://gitlab.mafengwo.com/mobiledev/travelguide-docs'

# Default categories (in order) to appear in the navigation
sections: [
    ['product', '产品需求文档'],
    ['entity', '业务实体描述文档'],
    ['data', '后台数据接口文档'],
    ['ios', 'iOS项目文档'],
    ['android', 'Android项目文档'],
    ['team', '团队相关文档'],
    ['help', '帮助']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''
# image Url defined by mengsong
imageurl: '/assets/img'
# Dates are not included in permalinks
permalink: none 

timezone: Asia/Shanghai

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
# markdown: redcarpet
# redcarpet:
#    extensions: [
#       'no_intra_emphasis',
#        'fenced_code_blocks',
#        'autolink',
#        'strikethrough',
#        'superscript',
#        'with_toc_data',
#        'tables',
#        'hardwrap'
#    ]
markdown: kramdown
dramdown:
    input:GFW
    use_coderay:true
    
excerpt_separator: ""

# toc plugin
minItemsToShowToc: 0
showToggleButton: true 

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
 provider :false
  #google : 
      #tracking_id : 'UA-123-12'
  #getclicky :
    #site_id :

showToggleButton: true


